In [2]:
import numpy as np

In [3]:
hvList = [1,2,3,4,5]

In [4]:
numpyList = np.array(hvList)

In [5]:
numpyList

array([1, 2, 3, 4, 5])

# Built-in methods

## arange

In [6]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
np.arange(3,20)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
np.arange(3,20,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [10]:
range(3,20,2)

range(3, 20, 2)

In [11]:
for n in range(3,20,2):
  print(n)

3
5
7
9
11
13
15
17
19


In [12]:
list(range(3,20,2))

[3, 5, 7, 9, 11, 13, 15, 17, 19]

## linspace

In [13]:
np.linspace(3,20,2)

array([ 3., 20.])

In [14]:
np.linspace(3,20,10)

array([ 3.        ,  4.88888889,  6.77777778,  8.66666667, 10.55555556,
       12.44444444, 14.33333333, 16.22222222, 18.11111111, 20.        ])

In [15]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [16]:
np.linspace(0,10)     #50 is default

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [17]:
np.linspace(0,10, dtype=int)

array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,
        3,  3,  3,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  6,  6,  6,  6,
        6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9, 10])

## zeros

In [18]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [19]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
np.zeros(10, dtype=bool)

array([False, False, False, False, False, False, False, False, False,
       False])

In [21]:
np.zeros(10, dtype=str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

## ones

In [22]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.ones(10, dtype=bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## full

In [25]:
np.full(10, '')

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [26]:
np.full(10, False)

array([False, False, False, False, False, False, False, False, False,
       False])

In [27]:
np.full(10, 'steve')

array(['steve', 'steve', 'steve', 'steve', 'steve', 'steve', 'steve',
       'steve', 'steve', 'steve'], dtype='<U5')

In [28]:
a = np.full((2,4,3), 255)
a

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]])

In [31]:
a[:,:,0] = 255    # red
a[:,:,1] = 0    # green
a[:,:,2] = 0    # blue
a

array([[[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]]])